### ISSUE TITLE
how to run?

### ISSUE THREAD

**Issue by wojtekpolska** [BySuspect/AutoPixAiCreditClaimer#1]
there is no release in this repo, not sure how to run, and what to even download? not rly familiar with c#

**Comment by BySuspect** [comment]
This is just the initial version of the code, focused solely on automation. I will work on creating a better and more user-friendly version for release, but unfortunately, I currently don't have the time to do so. It might take a while before I can complete it.

**Comment by BySuspect** [comment]
@wojtekpolska Hello, you can quickly download and use an easy-to-use version from [here](https://github.com/BySuspect/AutoPixAiCreditClaimer/releases/latest) if you get an error, report it by opening a new issue.
