### ISSUE TITLE
Popup

### ISSUE THREAD

**Issue by Schumilex5** [BySuspect/AutoPixAiCreditClaimer#11]
Hello.
There is a new pop up that wants you to login in the app after logging in.
You have to manually close this sadly every time it logs in, making the claim process a bit tedious even automated.

**Comment by BySuspect** [comment]
oky i will fix it today

**Comment by BySuspect** [comment]
automation is broke rn but there is not new popup, can you send any screenshot?

**Comment by Schumilex5** [comment]
Sure. It is working fine now with your update now tho, thanks.
![image](https://github.com/BySuspect/AutoPixAiCreditClaimer/assets/91950344/ff06ec48-dcde-4110-a385-eda4f919e132)

this was it's html:
<div class="w-full h-full p-4 sm:py-6"><h1 class="text-3xl font-bold font-inter px-2 sm:px-4">PixAI App</h1><h2 class="text-xl font-inter px-2 sm:px-4">download to earn 30k credits</h2><button class="sc-iBYQkv dVmFAe MuiButtonBase-root sc-ftTHYK dfAnPH MuiIconButton-root MuiIconButton-sizeMedium absolute top-2 right-2 text-gray-500" tabindex="0" type="button"><svg viewBox="0 0 24 24" width="1.2em" height="1.2em"><path fill="currentColor" d="M19 6.41L17.59 5L12 10.59L6.41 5L5 6.41L10.59 12L5 17.59L6.41 19L12 13.41L17.59 19L19 17.59L13.41 12z"></path></svg><span class="sc-jSUZER iEASIj MuiTouchRipple-root"></span></button><section class="p-2 sm:p-4"><div class="h-[260px] w-full"><img class="h-full w-full object-cover" src="https://images-ng.pixai.art/images/thumb/03bd4288-68f7-4194-9585-3a43ea924e30" alt="cover"></div><p class="mt-4 font-inter"><p>Sign in on the PixAI App to claim <strong>30,000</strong> extra credits! One-time offer. Effective from January 31, 2024 12:30 pm (GMT+8)</p>
</p></section><section class="flex flex-wrap justify-between px-2 sm:px-4"><a class="h-[60px] mb-4" href="https://play.google.com/store/apps/details?id=io.mewtant.pixaiart&amp;listing=pixaiweb-app" rel="noopener noreferrer" target="_blank"><img class="dark:hidden h-full" src="https://cdn.pixai.art/artifacts/app-9af7d03bcc4e2243489e449079ff9f29dd2287a3/assets/google-play-badge-light-Ge2AoOPo.svg" alt="google-play-badge"><img class="hidden dark:block h-full" src="https://cdn.pixai.art/artifacts/app-9af7d03bcc4e2243489e449079ff9f29dd2287a3/assets/google-play-badge-dark-zJR0A5ub.svg" alt="google-play-badge"></a><a class="h-[60px]" href="https://apps.apple.com/app/pixai-ai-anime-art-generator/id6474528911" rel="noopener noreferrer" target="_blank"><img class="dark:hidden h-full" src="https://cdn.pixai.art/artifacts/app-9af7d03bcc4e2243489e449079ff9f29dd2287a3/assets/app-store-badge-light-6Y0da9Xp.svg" alt="app-store-badge"><img class="hidden dark:block h-full" src="https://cdn.pixai.art/artifacts/app-9af7d03bcc4e2243489e449079ff9f29dd2287a3/assets/app-store-badge-dark-AlcitE-D.svg" alt="app-store-badge"></a></section></div>

in the old version this is where it was stuck and had to be closed by hand, they started doing it for a few weeks now, but your new version handled it well now.

**Comment by Schumilex5** [comment]
Sure. It is working fine now with your update now tho, thanks.
![image](https://github.com/BySuspect/AutoPixAiCreditClaimer/assets/91950344/ff06ec48-dcde-4110-a385-eda4f919e132)

this was it's html:

```
<div class="w-full h-full p-4 sm:py-6"><h1 class="text-3xl font-bold font-inter px-2 sm:px-4">PixAI App</h1><h2 class="text-xl font-inter px-2 sm:px-4">download to earn 30k credits</h2><button class="sc-iBYQkv dVmFAe MuiButtonBase-root sc-ftTHYK dfAnPH MuiIconButton-root MuiIconButton-sizeMedium absolute top-2 right-2 text-gray-500" tabindex="0" type="button"><svg viewBox="0 0 24 24" width="1.2em" height="1.2em"><path fill="currentColor" d="M19 6.41L17.59 5L12 10.59L6.41 5L5 6.41L10.59 12L5 17.59L6.41 19L12 13.41L17.59 19L19 17.59L13.41 12z"></path></svg><span class="sc-jSUZER iEASIj MuiTouchRipple-root"></span></button><section class="p-2 sm:p-4"><div class="h-[260px] w-full"><img class="h-full w-full object-cover" src="https://images-ng.pixai.art/images/thumb/03bd4288-68f7-4194-9585-3a43ea924e30" alt="cover"></div><p class="mt-4 font-inter"><p>Sign in on the PixAI App to claim <strong>30,000</strong> extra credits! One-time offer. Effective from January 31, 2024 12:30 pm (GMT+8)</p>
</p></section><section class="flex flex-wrap justify-between px-2 sm:px-4"><a class="h-[60px] mb-4" href="https://play.google.com/store/apps/details?id=io.mewtant.pixaiart&amp;listing=pixaiweb-app" rel="noopener noreferrer" target="_blank"><img class="dark:hidden h-full" src="https://cdn.pixai.art/artifacts/app-9af7d03bcc4e2243489e449079ff9f29dd2287a3/assets/google-play-badge-light-Ge2AoOPo.svg" alt="google-play-badge"><img class="hidden dark:block h-full" src="https://cdn.pixai.art/artifacts/app-9af7d03bcc4e2243489e449079ff9f29dd2287a3/assets/google-play-badge-dark-zJR0A5ub.svg" alt="google-play-badge"></a><a class="h-[60px]" href="https://apps.apple.com/app/pixai-ai-anime-art-generator/id6474528911" rel="noopener noreferrer" target="_blank"><img class="dark:hidden h-full" src="https://cdn.pixai.art/artifacts/app-9af7d03bcc4e2243489e449079ff9f29dd2287a3/assets/app-store-badge-light-6Y0da9Xp.svg" alt="app-store-badge"><img class="hidden dark:block h-full" src="https://cdn.pixai.art/artifacts/app-9af7d03bcc4e2243489e449079ff9f29dd2287a3/assets/app-store-badge-dark-AlcitE-D.svg" alt="app-store-badge"></a></section></div>
```

in the old version this is where it was stuck and had to be closed by hand, they started doing it for a few weeks now, but your new version handled it well now.
