### ISSUE TITLE
bug when trying to claim

### ISSUE THREAD

**Issue by Tricklander** [BySuspect/AutoPixAiCreditClaimer#12]
![image](https://github.com/BySuspect/AutoPixAiCreditClaimer/assets/98157136/19f126c9-cf20-4ddb-a324-f9d2df5a270c)

**Comment by BySuspect** [comment]
this is bug from windows just press continue or reopen program

**Comment by Tricklander** [comment]
![image](https://github.com/BySuspect/AutoPixAiCreditClaimer/assets/98157136/71500a04-2712-490a-ba99-b8dabe736136)
does not click on email and is stuck on this page upon manually clicking email rest works fine

**Comment by BySuspect** [comment]
hmm this is new i will fix this but not soon, i reset my computer so i have to install all things for developing

**Comment by BySuspect** [comment]
i fixed and uploaded new release you can download [here](https://github.com/BySuspect/AutoPixAiCreditClaimer/releases/latest)

**Comment by Tricklander** [comment]
alright ill try it later and tell!
