### ISSUE TITLE
Claiming credits is not working

### ISSUE THREAD

**Issue by Harabe-x** [BySuspect/AutoPixAiCreditClaimer#2]
The whole process starts, only that at the end the credits are not collected,btw 
if you want i can help you rewrite the whole code because it is very unreadable and hard to debug

**Comment by BySuspect** [comment]
> The whole process starts, only that at the end the credits are not collected,btw if you want i can help you rewrite the whole code because it is very unreadable and hard to debug

i think its working fine, because im using it daily, I haven't released the latest update as a release, maybe there is a bug in the v1.0.3, maybe I will update it to a new version.

**Comment by Harabe-x** [comment]
https://github.com/BySuspect/AutoPixAiCreditClaimer/assets/105777605/a7053645-cc72-448a-a294-bffc3d94818f

Not working, here is a video

**Comment by BySuspect** [comment]
oh its some times bugging, maybe a rate limit or something happening. I was look my accounts and last credit claim log is 3 days ago but im using daily, probably pixai moderators made something for hard any automations. Im looking for what is this issue.

**Comment by BySuspect** [comment]
@Harabe-x  can u try this, im added delay after claim click and its worked on me

[AutoPixAiCreditClaimer.zip](https://github.com/BySuspect/AutoPixAiCreditClaimer/files/12261577/AutoPixAiCreditClaimer.zip)
