### ISSUE TITLE
Credit claim not working

### ISSUE THREAD

**Issue by Tricklander** [BySuspect/AutoPixAiCreditClaimer#3]
i start the claim process it opens multiple command windows and then says process complete with each command window stuck
![image](https://github.com/BySuspect/AutoPixAiCreditClaimer/assets/98157136/b2e79f17-01d5-4811-89cf-df21f2a0789f)

**Comment by BySuspect** [comment]
Did you click once or did you click more than once?

**Comment by Tricklander** [comment]
once

**Comment by BySuspect** [comment]
can you send me your last logs on `C:\Users\User\Documents\PixaiCreditClaimer\Logs`

**Comment by Tricklander** [comment]
[Log2023-08-19-22-21-28.txt](https://github.com/BySuspect/AutoPixAiCreditClaimer/files/12388906/Log2023-08-19-22-21-28.txt)

**Comment by Tricklander** [comment]
[Log2023-08-20-21-13-13.txt](https://github.com/BySuspect/AutoPixAiCreditClaimer/files/12388909/Log2023-08-20-21-13-13.txt)

**Comment by BySuspect** [comment]
this is chrome driver error your chrome version is to high

**Comment by Tricklander** [comment]
what do i do?

**Comment by BySuspect** [comment]
im looking for how to fix it

**Comment by BySuspect** [comment]
can you try this im updated library version maybe will fix it your problem  [AutoPixAiCreditClaimer.zip](https://github.com/BySuspect/AutoPixAiCreditClaimer/files/12388922/AutoPixAiCreditClaimer.zip)

 @Tricklander

**Comment by Tricklander** [comment]
it works thanks!
