### ISSUE TITLE
stuck wont go to credits tab

### ISSUE THREAD

**Issue by Tricklander** [BySuspect/AutoPixAiCreditClaimer#4]
worked yesterday today it doesnt move to credits tab
![image](https://github.com/BySuspect/AutoPixAiCreditClaimer/assets/98157136/0867b79a-b4eb-4611-bc3a-dd96409c055e)

**Comment by BySuspect** [comment]
haha what a timing, pixai site owners is made change at profiles so its bugged, I will fix it and publish new release in a hour i think

**Comment by BySuspect** [comment]
can you try this probly i fixed problem [AutoPixAiCreditClaimer.zip](https://github.com/BySuspect/AutoPixAiCreditClaimer/files/12393217/AutoPixAiCreditClaimer.zip)
 
@Tricklander

**Comment by Tricklander** [comment]
It works thanks again!
I thought I'd let you know that this is not really an issue but sometimes the bot double clicks the credit claim button causing it to claim and then send a notification saying that you have already claimed today, it doesn't alter the claiming process but I just thought I would share it.
