### ISSUE TITLE
New Issue, no claiming

### ISSUE THREAD

**Issue by WarW0lf** [BySuspect/AutoPixAiCreditClaimer#5]
Hello,

your program starts normally but the last step to claim itself freezes it.

I don't know if it is a language problem or something.

![Screenshot 2023-08-27 131320](https://github.com/BySuspect/AutoPixAiCreditClaimer/assets/131314002/aed25b6f-d238-4980-8337-b9572736a9fc)

**Comment by BySuspect** [comment]
can you send me your last logs on `C:\Users\User\Documents\PixaiCreditClaimer\Logs`

**Comment by WarW0lf** [comment]
here the last four 

[Log2023-08-26-20-01-36.txt](https://github.com/BySuspect/AutoPixAiCreditClaimer/files/12448155/Log2023-08-26-20-01-36.txt)
[Log2023-08-27-13-11-22.txt](https://github.com/BySuspect/AutoPixAiCreditClaimer/files/12448156/Log2023-08-27-13-11-22.txt)
[Log2023-08-27-13-13-55.txt](https://github.com/BySuspect/AutoPixAiCreditClaimer/files/12448157/Log2023-08-27-13-13-55.txt)
[Log2023-08-25-11-18-47.txt](https://github.com/BySuspect/AutoPixAiCreditClaimer/files/12448158/Log2023-08-25-11-18-47.txt)

**Comment by BySuspect** [comment]
are you using last version on app?

**Comment by WarW0lf** [comment]
yes

**Comment by BySuspect** [comment]
can you re install last version and try again because i already fixed this bug i think you are using old one

**Comment by WarW0lf** [comment]
ok i try it again, with the last one from 21. aug, same result

![Screenshot 2023-08-27 163424](https://github.com/BySuspect/AutoPixAiCreditClaimer/assets/131314002/9c72b5db-df95-4371-a36d-22f4f38922d5)

[Log2023-08-27-16-33-54.txt](https://github.com/BySuspect/AutoPixAiCreditClaimer/files/12448199/Log2023-08-27-16-33-54.txt)

**Comment by BySuspect** [comment]
can you try this: [AutoPixAiCreditClaimer.zip](https://github.com/BySuspect/AutoPixAiCreditClaimer/files/12448208/AutoPixAiCreditClaimer.zip) if its not work idk how to fix it i want search for this and will take a while

**Comment by WarW0lf** [comment]
ok its working, thanks :)

**Comment by WarW0lf** [comment]
Hi, I reopen this thread. Because I use the neu version (Version from 21.09. from the other thread) but it has the same Issue

Chrome start, but the site doesnt switch to credit site, it stuck on the main page

![Screenshot 2023-09-22 123131](https://github.com/BySuspect/AutoPixAiCreditClaimer/assets/131314002/1ee00e09-7afc-4b16-815a-3ed751773324)

and yes, I have already reinstalled the current version

**Comment by BySuspect** [comment]
you are using version 1.1.0 right?

**Comment by BySuspect** [comment]
now im tried and its bugged again so im looking for fix

**Comment by WarW0lf** [comment]
if its the Version from the yesturday issue thread https://github.com/BySuspect/AutoPixAiCreditClaimer/issues/7

then yes

**Comment by BySuspect** [comment]
can you try this: [AutoPixAiCreditClaimer.zip](https://github.com/BySuspect/AutoPixAiCreditClaimer/files/12700140/AutoPixAiCreditClaimer.zip)

**Comment by WarW0lf** [comment]
no still same Issue
![Screenshot 2023-09-22 132918](https://github.com/BySuspect/AutoPixAiCreditClaimer/assets/131314002/da6dd2d5-3030-4a41-a9e0-d0216bc9db35)

**Comment by BySuspect** [comment]
oky probly i fixed it its works fine try this: [AutoPixAiCreditClaimer.zip](https://github.com/BySuspect/AutoPixAiCreditClaimer/files/12700357/AutoPixAiCreditClaimer.zip)

**Comment by WarW0lf** [comment]
yes, works perfect :)
