### ISSUE TITLE
error not claiming

### ISSUE THREAD

**Issue by Tricklander** [BySuspect/AutoPixAiCreditClaimer#6]
![image](https://github.com/BySuspect/AutoPixAiCreditClaimer/assets/98157136/c6095aaf-c007-41f2-9b0f-fa70784e5f40)
help

**Comment by BySuspect** [comment]
this is a bug. can you try this [AutoPixAiCreditClaimer.zip](https://github.com/BySuspect/AutoPixAiCreditClaimer/files/12448208/AutoPixAiCreditClaimer.zip)

**Comment by Tricklander** [comment]
it works thanks!

**Comment by Tricklander** [comment]
just a suggestion can you add auto quit as an option like after it finishes claiming?
