### ISSUE TITLE
Error device interface

### ISSUE THREAD

**Issue by Monty1204** [BySuspect/AutoPixAiCreditClaimer#7]
Hello,

It's the first time I try it and it doesn't seem to work. When I launch it app, it opens the web browers, logs in the account but never reaches the credit page. Then the following error appears in the console and I can't find what's the cause of it...

![image](https://github.com/BySuspect/AutoPixAiCreditClaimer/assets/145705892/f940d5eb-3383-4678-8197-e7ef5c672807)

Thanks you in advance for the help!

**Comment by BySuspect** [comment]
pixai site owners made a change on website so its bugged im looking for fix now

**Comment by BySuspect** [comment]
can you try this: [AutoPixAiCreditClaimer.zip](https://github.com/BySuspect/AutoPixAiCreditClaimer/files/12690382/AutoPixAiCreditClaimer.zip)

**Comment by Monty1204** [comment]
Worked, thanks you!
