### ISSUE TITLE
Program doesn't claim any more, site change settings

### ISSUE THREAD

**Issue by WarW0lf** [BySuspect/AutoPixAiCreditClaimer#8]
Hi, 

PixAI changed their settings again. Any solutions?

![Bild_2024-01-12_120315442](https://github.com/BySuspect/AutoPixAiCreditClaimer/assets/131314002/dde2dd94-dea1-4260-b058-1b2c412a4944)

**Comment by BySuspect** [comment]
@WarW0lf I will fix it and release a new version, but it will take some time.

**Comment by BySuspect** [comment]
@WarW0lf can you try this: 
[AutoPixAiCreditClaimer.zip](https://github.com/BySuspect/AutoPixAiCreditClaimer/files/13927389/AutoPixAiCreditClaimer.zip)

**Comment by WarW0lf** [comment]
it works :)
