### ISSUE TITLE
Buggs

### ISSUE THREAD

**Issue by Tricklander** [BySuspect/AutoPixAiCreditClaimer#9]
![image](https://github.com/BySuspect/AutoPixAiCreditClaimer/assets/98157136/14e3c39c-554d-40b8-bb4d-1a46abdd06d3)
this thing **stops the bot** and **it doesn't close the browser when done**

**Comment by Tricklander** [comment]
like i mean when i cancelled the ad it would claim and then not close the browser

**Comment by BySuspect** [comment]
oky i will fix it today

**Comment by BySuspect** [comment]
Can you try this: 
[AutoPixAiCreditClaimer.zip](https://github.com/BySuspect/AutoPixAiCreditClaimer/files/14228662/AutoPixAiCreditClaimer.zip)

**Comment by BySuspect** [comment]
Clossing issue for inactivity.

**Comment by Tricklander** [comment]
![Uploading image.png…]()
bro

**Comment by Tricklander** [comment]
sorry was not using the device for a while

**Comment by BySuspect** [comment]
dont open browser full screen

**Comment by Tricklander** [comment]
![image](https://github.com/BySuspect/AutoPixAiCreditClaimer/assets/98157136/0b94fa73-8d64-4f45-9dc1-a248f01835af)

**Comment by BySuspect** [comment]
omg what a annoying thing is it im trying to fix this issue

**Comment by BySuspect** [comment]
can you try this: 
[AutoPixAiCreditClaimer.zip](https://github.com/BySuspect/AutoPixAiCreditClaimer/files/14237315/AutoPixAiCreditClaimer.zip)

**Comment by BySuspect** [comment]
The browser should be at these dimensions. Normally, do you make it full screen or does it open full screen for you?
![image](https://github.com/BySuspect/AutoPixAiCreditClaimer/assets/70052500/eaf6b0e2-ad15-45cf-be8d-820df0f56f77)

**Comment by BySuspect** [comment]
> can you try this: [AutoPixAiCreditClaimer.zip](https://github.com/BySuspect/AutoPixAiCreditClaimer/files/14237315/AutoPixAiCreditClaimer.zip)

**Comment by Tricklander** [comment]
> The browser should be at these dimensions. Normally, do you make it full screen or does it open full screen for you? ![image](https://private-user-images.githubusercontent.com/70052500/304023025-eaf6b0e2-ad15-45cf-be8d-820df0f56f77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MzQ3MjgsIm5iZiI6MTcwNzczNDQyOCwicGF0aCI6Ii83MDA1MjUwMC8zMDQwMjMwMjUtZWFmNmIwZTItYWQxNS00NWNmLWJlOGQtODIwZGYwZjU2Zjc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDEwNDAyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0YTBhN2YxMmQzMWRiMjIyMDFmZTBkNjIxNDhjYWY0ZTAwMjM0Y2IwNGQwOWY3MGNiZjJmN2VlZDUwNDMyMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lw3rSayDXjNaGEXgCgQsCS-JQcxP813F4MNKkPachGU)

i dont really make it fullscreen or any for that matter, i was just testing whether it was workin or nah

**Comment by Tricklander** [comment]
it works!!! thx
